export const productsTypes = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT'
}